### PR TITLE
can now remove listeners add via once(), and off() treats "" as a val…

### PR DESCRIPTION
**Pull request by JoshuaWise**
I've fixed a few cases of misbehavior:
- `.off("", func)` removes all event listeners for every event, so you can not remove listeners with falsey event names. Now, you can no longer add listeners with falsey event names, bringing consistency to how event-lite treats falsey events.
- Previously, `.off(type, func)` could not remove event listeners that were added by `.once()`, because `.once()` would wrap the original function. Now it works properly.

### CODE REVIEW

**Comment by kawanet** [comment]
I agree with the principle that the most of key features have enough compatibility with the official EventEmitter module when the event-lite module could keep it simplicity.

> - Previously, .off("", func) would remove all event listeners for every event. Now, it behaves correctly and treats "" as a valid event name.

It's correct.
Previously, event-lite ignores falsy event names. 
EventEmitter allows them, such as zero length string `""`, numeric `0`, boolean `false`, (and even `null` and `undefined` surprisingly) etc, on the other hand. 

> - Previously, .off(type, func) could not remove event listeners that were added by .once(), because .once() would wrap the original function. Now it works properly.

Thanks (again). That's a bug.

**Comment by JoshuaWise** [comment]
If EventLite should ignore falsey event names, then it should do so everywhere. So with my recent commit, I made all of EventLite's methods equally ignore falsey event names, instead of just the `.off()` method. You can no longer add listeners with falsey event names.

**Comment by kawanet** [comment]
I understand that EventLite should allow falsy event names as EventEmitter allows them. Your previous commit 370cf43 is correct. Could you please revert that last commit  ba16f72 except for the diff below:

``` diff
 -      return test !== func && (!test.originalListener || test.originalListener !== func);
 +      return test !== func &&  test.originalListener !== func;
```

I'll marge it then.

**Comment by JoshuaWise** [comment]
Okay, sure, that works for me.

**Comment by JoshuaWise** [comment]
I believe it's ready to be merged now.

**Pull request merged**
